const number = (name, fallback) => {
  const value = Number(process.env[name]);
  return Number.isFinite(value) ? value : fallback;
};

const bool = (name, fallback = false) => {
  const value = process.env[name];
  if (value == null) return fallback;
  return value === "true" || value === "1";
};

export const config = Object.freeze({
  port: number("PORT", 4310),
  deepseek: {
    apiKey: process.env.DEEPSEEK_API_KEY || "",
    baseUrl: process.env.DEEPSEEK_BASE_URL || "https://api.deepseek.com",
    model: process.env.DEEPSEEK_MODEL || "deepseek-chat"
  },
  execution: {
    mode: process.env.EXECUTION_MODE || "paper",
    autonomousEnabled: bool("AUTONOMOUS_ENABLED", false),
    attributionVerified: bool("BOOST_ATTRIBUTION_VERIFIED", false),
    cycleMs: number("AUTONOMOUS_CYCLE_MS", 300000),
    marketPollMs: number("MARKET_POLL_MS", 30000),
    positionMonitorMs: number("POSITION_MONITOR_MS", 30000),
    aiAnalysisIntervalMs: number("AI_ANALYSIS_INTERVAL_MS", 120000),
    adaptiveTimingEnabled: bool("ADAPTIVE_TIMING_ENABLED", true),
    adaptiveEvaluationMs: number("ADAPTIVE_EVALUATION_MS", 3600000),
    priceWindowSamples: number("PRICE_WINDOW_SAMPLES", 48),
    targetVolumeUsd: number("BOOST_TARGET_VOLUME_USD", 650),
    maxCampaignCostsUsd: number("MAX_CAMPAIGN_COSTS_USD", 10),
    minSignalBps: number("MIN_SIGNAL_BPS", 18),
    maxEntryDowntrendBps: number("MAX_ENTRY_DOWNTREND_BPS", 5),
    maxPositionMinutes: number("MAX_POSITION_MINUTES", 45),
    takeProfitBps: number("TAKE_PROFIT_BPS", 22),
    stopLossBps: number("STOP_LOSS_BPS", 35),
    hardStopLossBps: number("HARD_STOP_LOSS_BPS", 40),
    recoveryMaxMinutes: number("RECOVERY_MAX_MINUTES", 30),
    maxExecutionCostBps: number("MAX_EXECUTION_COST_BPS", 150),
    maxEffectiveCostBps: number("MAX_EFFECTIVE_COST_BPS", 5),
    maxRewardSubsidyBps: number("MAX_REWARD_SUBSIDY_BPS", 150),
    minNetEdgeBps: number("MIN_NET_EDGE_BPS", 1),
    maxRoundTripLossBps: number("MAX_ROUND_TRIP_LOSS_BPS", 15),
    maxEntryRoundTripLossBps: number("MAX_ENTRY_ROUND_TRIP_LOSS_BPS", 12),
    minEntryEfficiencyBps: number("MIN_ENTRY_EFFICIENCY_BPS", 0.5),
    minGridLayerSpacingBps: number("MIN_GRID_LAYER_SPACING_BPS", 3),
    maxExecutableQuoteAgeMs: number("MAX_EXECUTABLE_QUOTE_AGE_MS", 90000),
    offHoursMaxTradeUsd: number("OFF_HOURS_MAX_TRADE_USD", 50),
    extendedHoursExtraEdgeBps: number("EXTENDED_HOURS_EXTRA_EDGE_BPS", 2),
    closedHoursExtraEdgeBps: number("CLOSED_HOURS_EXTRA_EDGE_BPS", 4),
    minNetEntryBps: number("MIN_NET_ENTRY_BPS", 10),
    mediumSizeNetEntryBps: number("MEDIUM_SIZE_NET_ENTRY_BPS", 6),
    smallSizeNetEntryBps: number("SMALL_SIZE_NET_ENTRY_BPS", 3),
    minNetExitBps: number("MIN_NET_EXIT_BPS", 10),
    tokenLossStreakLimit: number("TOKEN_LOSS_STREAK_LIMIT", 2),
    tokenCooldownMinutes: number("TOKEN_COOLDOWN_MINUTES", 60),
    maxGridLotsPerToken: number("MAX_GRID_LOTS_PER_TOKEN", 4),
    maxOpenGridLots: number("MAX_OPEN_GRID_LOTS", 20),
    executableQuoteMinSamples: number("EXECUTABLE_QUOTE_MIN_SAMPLES", 3),
    executableQuoteWindowSamples: number("EXECUTABLE_QUOTE_WINDOW_SAMPLES", 24),
    nvdaEntrySignalBps: number("NVDA_ENTRY_SIGNAL_BPS", 1),
    sndkEntrySignalBps: number("SNDK_ENTRY_SIGNAL_BPS", 30),
    spcxEntrySignalBps: number("SPCX_ENTRY_SIGNAL_BPS", 10),
    crclEntrySignalBps: number("CRCL_ENTRY_SIGNAL_BPS", 15),
    skhyEntrySignalBps: number("SKHY_ENTRY_SIGNAL_BPS", 10),
    maxProjectedLossPerTradeUsd: number("MAX_PROJECTED_LOSS_PER_TRADE_USD", 0.75),
    minDynamicTradeUsd: number("MIN_DYNAMIC_TRADE_USD", 50),
    tokenTradeCapsUsd: Object.freeze({
      NVDAx: number("MAX_TRADE_NVDA_USD", 330),
      SNDKx: number("MAX_TRADE_SNDK_USD", 50),
      SPCXx: number("MAX_TRADE_SPCX_USD", 0),
      CRCLx: number("MAX_TRADE_CRCL_USD", 0),
      SKHYx: number("MAX_TRADE_SKHY_USD", 0)
    })
  },
  risk: {
    totalCapitalUsd: number("TOTAL_CAPITAL_USD", 1000),
    baseCapitalUsd: number("BASE_CAPITAL_USD", number("TOTAL_CAPITAL_USD", 1000)),
    maxTradeUsd: number("MAX_TRADE_USD", 50),
    maxTotalRwaExposurePct: number("MAX_TOTAL_RWA_EXPOSURE_PCT", 30),
    maxTokenPositionPct: number("MAX_TOKEN_POSITION_PCT", 10),
    maxSlippageBps: number("MAX_SLIPPAGE_BPS", 15),
    minBroadcastIntervalMs: number("MIN_BROADCAST_INTERVAL_MS", 60000),
    dailyLossLimitPct: number("DAILY_LOSS_LIMIT_PCT", 2),
    maxTradesPerHour: number("MAX_TRADES_PER_HOUR", 6)
  },
  aeon: {
    enabled: bool("AEON_ENABLED", true),
    autonomousEnabled: bool("AEON_AUTONOMOUS_ENABLED", true),
    attributionVerified: bool("AEON_ATTRIBUTION_VERIFIED", false),
    cycleMs: number("AEON_CYCLE_MS", 30000),
    marketPollMs: number("AEON_MARKET_POLL_MS", 15000),
    positionMonitorMs: number("AEON_POSITION_MONITOR_MS", 20000),
    maxTradeUsd: number("AEON_MAX_TRADE_USD", 150),
    maxExposureUsd: number("AEON_MAX_EXPOSURE_USD", 400),
    entryDipBps: number("AEON_ENTRY_DIP_BPS", 30),
    exitGainBps: number("AEON_EXIT_GAIN_BPS", 100),
    stopLossBps: number("AEON_STOP_LOSS_BPS", 200),
    gridSpacingBps: number("AEON_GRID_SPACING_BPS", 60),
    maxGridLots: number("AEON_MAX_GRID_LOTS", 1),
    maxOpenLots: number("AEON_MAX_OPEN_LOTS", 1),
    minEntryNetEdgeBps: number("AEON_MIN_ENTRY_NET_EDGE_BPS", 15),
    minBidTrendBps: number("AEON_MIN_BID_TREND_BPS", -5),
    minSellNetExitBps: number("AEON_MIN_SELL_NET_EXIT_BPS", 20),
    maxRoundTripLossBps: number("AEON_MAX_ROUND_TRIP_LOSS_BPS", 40),
    maxExecutionCostBps: number("AEON_MAX_EXECUTION_COST_BPS", 100),
    maxQuoteAgeMs: number("AEON_MAX_QUOTE_AGE_MS", 90000),
    minSamples: number("AEON_MIN_SAMPLES", 3),
    sampleWindow: number("AEON_SAMPLE_WINDOW", 24),
    minBroadcastIntervalMs: number("AEON_MIN_BROADCAST_INTERVAL_MS", 20000),
    maxSlippageBps: number("AEON_MAX_SLIPPAGE_BPS", 20),
    maxGasPriceGwei: number("AEON_MAX_GAS_PRICE_GWEI", 8),
    maxGasCostUsdPerSwap: number("AEON_MAX_GAS_COST_USD_PER_SWAP", 1.0),
    maxCampaignCostsUsd: number("AEON_MAX_CAMPAIGN_COSTS_USD", 50),
    maxLossUsd: number("AEON_MAX_LOSS_USD", 20),
    targetVolumeUsd: number("AEON_TARGET_VOLUME_USD", 50000),
    initialVolumeUsd: number("AEON_INITIAL_VOLUME_USD", 0),
    leaderboardRows: number("AEON_LEADERBOARD_ROWS", 20)
  },
  maker: {
    enabled: bool("MAKER_ENABLED", true),
    autonomousEnabled: bool("MAKER_AUTONOMOUS_ENABLED", true),
    mode: process.env.MAKER_MODE || "classic",
    cycleMs: number("MAKER_CYCLE_MS", 12000),
    token: process.env.MAKER_TOKEN || "NVDAx",
    tokenAddress: process.env.MAKER_TOKEN_ADDRESS || "0xc845b2894dbddd03858fd2d643b4ef725fe0849d",
    quoteAddress: process.env.MAKER_QUOTE_ADDRESS || "0x779ded0c9e1022225f8e0630b35a9b54be713736",
    legUsd: number("MAKER_LEG_USD", 200),
    buyTriggerBps: number("MAKER_BUY_TRIGGER_BPS", 3),
    sellTriggerBps: number("MAKER_SELL_TRIGGER_BPS", 3),
    fastExitTriggerBps: number("MAKER_FAST_EXIT_TRIGGER_BPS", 2),
    stopLossBps: number("MAKER_STOP_LOSS_BPS", 15),
    targetGainBps: number("MAKER_TARGET_GAIN_BPS", 10),
    maxHoldMs: number("MAKER_MAX_HOLD_MS", 120000),
    orderTtlMs: number("MAKER_ORDER_TTL_MS", 15000),
    maxInventoryUsd: number("MAKER_MAX_INVENTORY_USD", 240),
    priceDriftGuardBps: number("MAKER_PRICE_DRIFT_GUARD_BPS", 25),
    priceJumpGuardBps: number("MAKER_PRICE_JUMP_GUARD_BPS", 60),
    trendWindowMs: number("MAKER_TREND_WINDOW_MS", 300000),
    trendPauseBps: number("MAKER_TREND_PAUSE_BPS", 50),
    regimeWindowMs: number("MAKER_REGIME_WINDOW_MS", 7200000),
    regimeTrendBps: number("MAKER_REGIME_TREND_BPS", 50),
    regimeRangeMaxBps: number("MAKER_REGIME_RANGE_MAX_BPS", 300),
    regimeMinSamples: number("MAKER_REGIME_MIN_SAMPLES", 30),
    breakerAutoResume: bool("MAKER_BREAKER_AUTO_RESUME", true),
    breakerCheckMs: number("MAKER_BREAKER_CHECK_MS", 900000),
    breakerTrendBps: number("MAKER_BREAKER_TREND_BPS", -30),
    breakerRangeMaxBps: number("MAKER_BREAKER_RANGE_MAX_BPS", 300),
    breakerKlines: number("MAKER_BREAKER_KLINES", 24),
    marketHaltEnabled: bool("MAKER_MARKET_HALT_ENABLED", false),
    gridLevels: number("MAKER_GRID_LEVELS", 12),
    gridSpacingBps: number("MAKER_GRID_SPACING_BPS", 50),
    gridProfitBps: number("MAKER_GRID_PROFIT_BPS", 50),
    gridDeployPct: number("MAKER_GRID_DEPLOY_PCT", 55),
    gridOrderTtlMs: number("MAKER_GRID_ORDER_TTL_MS", 300000),
    gridAiTuning: bool("MAKER_GRID_AI_TUNING", true),
    gridAiIntervalMs: number("MAKER_GRID_AI_INTERVAL_MS", 3600000),
    gridRegimeTrendBps: number("MAKER_GRID_REGIME_TREND_BPS", 100),
    gridRegimeRangeMaxBps: number("MAKER_GRID_REGIME_RANGE_MAX_BPS", 600),
    pauseStartUtc: number("MAKER_PAUSE_START_UTC", 3),
    pauseEndUtc: number("MAKER_PAUSE_END_UTC", 7),
    maxLossUsd: number("MAKER_MAX_LOSS_USD", 15),
    lossStreakLimit: number("MAKER_LOSS_STREAK_LIMIT", 3),
    cooldownMinutes: number("MAKER_COOLDOWN_MINUTES", 10),
    cooldownRecheckMs: number("MAKER_COOLDOWN_RECHECK_MS", 300000),
    klineCheckMs: number("MAKER_KLINE_CHECK_MS", 60000),
    slippagePct: number("MAKER_SLIPPAGE_PCT", 0.15),
    exitMaxSlippageBps: number("MAKER_EXIT_MAX_SLIPPAGE_BPS", 50)
  }
});
